# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editar.ui'
#
# Created: Sat Apr 19 11:41:07 2014
#      by: pyside-uic 0.2.14 running on PySide 1.1.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(613, 433)
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.Informacion = QtGui.QWidget()
        self.Informacion.setObjectName("Informacion")
        self.gridLayout_2 = QtGui.QGridLayout(self.Informacion)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtGui.QLabel(self.Informacion)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../imagenes/icons126px/It-Infrastructure-Computer-icon.png"))
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 1, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.Informacion)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.Informacion)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtGui.QLabel(self.Informacion)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtGui.QLineEdit(self.Informacion)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.lineEdit_2 = QtGui.QLineEdit(self.Informacion)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.lineEdit_3 = QtGui.QLineEdit(self.Informacion)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout.addWidget(self.lineEdit_3)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 1, 1, 1)
        self.pushButton = QtGui.QPushButton(self.Informacion)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../imagenes/System-Save-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 1, 1, 1)
        self.tabWidget.addTab(self.Informacion, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../imagenes/icons126px/Computer-Hardware-Monitor-icon.png"))
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 1, 1, 1)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_6.addWidget(self.label_7)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 1, 0, 1, 1)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_7 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_5.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_5.addWidget(self.lineEdit_8)
        self.lineEdit_9 = QtGui.QLineEdit(self.tab_2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_5.addWidget(self.lineEdit_9)
        self.gridLayout_4.addLayout(self.verticalLayout_5, 1, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.tab_2)
        self.pushButton_3.setIcon(icon)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_4.addWidget(self.pushButton_3, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_17 = QtGui.QLabel(self.tab_3)
        self.label_17.setText("")
        self.label_17.setPixmap(QtGui.QPixmap("../imagenes/icons126px/Computer-Hardware-Keyboard-icon.png"))
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 0, 1, 1, 1)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_18 = QtGui.QLabel(self.tab_3)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_8.addWidget(self.label_18)
        self.label_19 = QtGui.QLabel(self.tab_3)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_8.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_8.addWidget(self.label_20)
        self.gridLayout_5.addLayout(self.verticalLayout_8, 1, 0, 1, 1)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.lineEdit_10 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_7.addWidget(self.lineEdit_10)
        self.lineEdit_11 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_7.addWidget(self.lineEdit_11)
        self.lineEdit_12 = QtGui.QLineEdit(self.tab_3)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_7.addWidget(self.lineEdit_12)
        self.gridLayout_5.addLayout(self.verticalLayout_7, 1, 1, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.tab_3)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_5.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setText("")
        self.label_21.setPixmap(QtGui.QPixmap("../imagenes/icons126px/Computer-Hardware-Mouse-icon.png"))
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 1, 1, 1)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_22 = QtGui.QLabel(self.tab_4)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_10.addWidget(self.label_22)
        self.label_23 = QtGui.QLabel(self.tab_4)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_10.addWidget(self.label_23)
        self.label_24 = QtGui.QLabel(self.tab_4)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_10.addWidget(self.label_24)
        self.gridLayout_6.addLayout(self.verticalLayout_10, 1, 0, 1, 1)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.lineEdit_15 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.verticalLayout_9.addWidget(self.lineEdit_15)
        self.lineEdit_14 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_9.addWidget(self.lineEdit_14)
        self.lineEdit_13 = QtGui.QLineEdit(self.tab_4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_9.addWidget(self.lineEdit_13)
        self.gridLayout_6.addLayout(self.verticalLayout_9, 1, 1, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.tab_4)
        self.pushButton_5.setIcon(icon)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_6.addWidget(self.pushButton_5, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_25 = QtGui.QLabel(self.tab_5)
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("../imagenes/icons126px/It-Infrastructure-Server-icon.png"))
        self.label_25.setObjectName("label_25")
        self.gridLayout_7.addWidget(self.label_25, 0, 1, 1, 1)
        self.verticalLayout_12 = QtGui.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_26 = QtGui.QLabel(self.tab_5)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_12.addWidget(self.label_26)
        self.label_27 = QtGui.QLabel(self.tab_5)
        self.label_27.setObjectName("label_27")
        self.verticalLayout_12.addWidget(self.label_27)
        self.label_28 = QtGui.QLabel(self.tab_5)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_12.addWidget(self.label_28)
        self.gridLayout_7.addLayout(self.verticalLayout_12, 1, 0, 1, 1)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.lineEdit_18 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.verticalLayout_11.addWidget(self.lineEdit_18)
        self.lineEdit_17 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.verticalLayout_11.addWidget(self.lineEdit_17)
        self.lineEdit_16 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.verticalLayout_11.addWidget(self.lineEdit_16)
        self.gridLayout_7.addLayout(self.verticalLayout_11, 1, 1, 1, 1)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_29 = QtGui.QLabel(self.tab_5)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.label_30 = QtGui.QLabel(self.tab_5)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_14.addWidget(self.label_30)
        self.label_31 = QtGui.QLabel(self.tab_5)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_14.addWidget(self.label_31)
        self.gridLayout_7.addLayout(self.verticalLayout_14, 1, 2, 1, 1)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.lineEdit_19 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.verticalLayout_13.addWidget(self.lineEdit_19)
        self.lineEdit_20 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.verticalLayout_13.addWidget(self.lineEdit_20)
        self.lineEdit_21 = QtGui.QLineEdit(self.tab_5)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.verticalLayout_13.addWidget(self.lineEdit_21)
        self.gridLayout_7.addLayout(self.verticalLayout_13, 1, 3, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.tab_5)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_7.addWidget(self.pushButton_6, 2, 1, 1, 3)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_35 = QtGui.QLabel(self.tab)
        self.label_35.setText("")
        self.label_35.setPixmap(QtGui.QPixmap("../imagenes/icons126px/Phones-Headset-icon.png"))
        self.label_35.setObjectName("label_35")
        self.gridLayout_8.addWidget(self.label_35, 0, 1, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_32 = QtGui.QLabel(self.tab)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_16.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.tab)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_16.addWidget(self.label_33)
        self.label_34 = QtGui.QLabel(self.tab)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_16.addWidget(self.label_34)
        self.gridLayout_8.addLayout(self.verticalLayout_16, 1, 0, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.lineEdit_22 = QtGui.QLineEdit(self.tab)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.verticalLayout_15.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtGui.QLineEdit(self.tab)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.verticalLayout_15.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtGui.QLineEdit(self.tab)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.verticalLayout_15.addWidget(self.lineEdit_24)
        self.gridLayout_8.addLayout(self.verticalLayout_15, 1, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.tab)
        self.pushButton_7.setIcon(icon)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_8.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", "Id:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "Sala:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "Perfil:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Informacion), QtGui.QApplication.translate("Form", "Información", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Modelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Form", "Nro. de serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_3.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Monitor", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Modelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Nro. de serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_4.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Teclado", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("Form", "Modelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("Form", "Nro. de serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Mouse", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("Form", "Marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("Form", "Modelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setText(QtGui.QApplication.translate("Form", "Nro. de serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setText(QtGui.QApplication.translate("Form", "S.O:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setText(QtGui.QApplication.translate("Form", "Procesador:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("Form", "Ram:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("Form", "Cpu", None, QtGui.QApplication.UnicodeUTF8))
        self.label_32.setText(QtGui.QApplication.translate("Form", "Marca:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("Form", "Modelo:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("Form", "Nro. de serie:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_7.setText(QtGui.QApplication.translate("Form", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Diadema", None, QtGui.QApplication.UnicodeUTF8))

